name: NiuMaManager
version: '1.0-SNAPSHOT'
main: mainFesht3.niuMaManager.NiuMaManager
api-version: '1.20'
commands:
  randomtp:
    description: 随机tp
    usage: /randomtp [help/do]
    permission: NiuMaManager.randomtp
    permission-message: 你没有使用此指令的权限
    visible: true  # 强制命令在 TAB 补全中显示